porter-stemmer stop\AbassiM.stp > stem\AbassiM.stm
porter-stemmer stop\AgricoleW.stp > stem\AgricoleW.stm
porter-stemmer stop\AliR.stp > stem\AliR.stm
porter-stemmer stop\AngCX.stp > stem\AngCX.stm
porter-stemmer stop\AngeloZ.stp > stem\AngeloZ.stm
porter-stemmer stop\AppadooD.stp > stem\AppadooD.stm
porter-stemmer stop\BenHasineA.stp > stem\BenHasineA.stm
porter-stemmer stop\BenssiN.stp > stem\BenssiN.stm
porter-stemmer stop\BhagatR.stp > stem\BhagatR.stm
porter-stemmer stop\BradyE.stp > stem\BradyE.stm
porter-stemmer stop\BriarsC.stp > stem\BriarsC.stm
porter-stemmer stop\Broadhurst.stp > stem\Broadhurst.stm
porter-stemmer stop\BronksA.stp > stem\BronksA.stm
porter-stemmer stop\BrownL.stp > stem\BrownL.stm
porter-stemmer stop\ChanaG.stp > stem\ChanaG.stm
porter-stemmer stop\ChanCK.stp > stem\ChanCK.stm
porter-stemmer stop\ChanWK.stp > stem\ChanWK.stm
porter-stemmer stop\CheangF.stp > stem\CheangF.stm
porter-stemmer stop\ChengLC.stp > stem\ChengLC.stm
porter-stemmer stop\ChewCH.stp > stem\ChewCH.stm
porter-stemmer stop\ChongJYH.stp > stem\ChongJYH.stm
porter-stemmer stop\ChongKV.stp > stem\ChongKV.stm
porter-stemmer stop\ChongL.stp > stem\ChongL.stm
porter-stemmer stop\CollingsM.stp > stem\CollingsM.stm
porter-stemmer stop\CollisC.stp > stem\CollisC.stm
porter-stemmer stop\DiamantopoulosG.stp > stem\DiamantopoulosG.stm
porter-stemmer stop\DongP.stp > stem\DongP.stm
porter-stemmer stop\EdwinO.stp > stem\EdwinO.stm
porter-stemmer stop\EftekhariS.stp > stem\EftekhariS.stm
porter-stemmer stop\EvansA.stp > stem\EvansA.stm
porter-stemmer stop\FooKSNEW.stp > stem\FooKSNEW.stm
porter-stemmer stop\Form.stp > stem\Form.stm
porter-stemmer stop\HaskellS.stp > stem\HaskellS.stm
porter-stemmer stop\HayatB.stp > stem\HayatB.stm
porter-stemmer stop\HengKK.stp > stem\HengKK.stm
porter-stemmer stop\HicksJ.stp > stem\HicksJ.stm
porter-stemmer stop\HoJW.stp > stem\HoJW.stm
porter-stemmer stop\HowlettA.stp > stem\HowlettA.stm
porter-stemmer stop\HughesP.stp > stem\HughesP.stm
porter-stemmer stop\JavaidMT.stp > stem\JavaidMT.stm
porter-stemmer stop\JiangS.stp > stem\JiangS.stm
porter-stemmer stop\JohalS.stp > stem\JohalS.stm
porter-stemmer stop\KallayT.stp > stem\KallayT.stm
porter-stemmer stop\KhanS.stp > stem\KhanS.stm
porter-stemmer stop\KhayumM.stp > stem\KhayumM.stm
porter-stemmer stop\KijakM.stp > stem\KijakM.stm
porter-stemmer stop\KoL.stp > stem\KoL.stm
porter-stemmer stop\KupusamyS.stp > stem\KupusamyS.stm
porter-stemmer stop\LaiYK.stp > stem\LaiYK.stm
porter-stemmer stop\LamC.stp > stem\LamC.stm
porter-stemmer stop\LamD.stp > stem\LamD.stm
porter-stemmer stop\LauEWF.stp > stem\LauEWF.stm
porter-stemmer stop\LeongJ.stp > stem\LeongJ.stm
porter-stemmer stop\LiC.stp > stem\LiC.stm
porter-stemmer stop\LimCL.stp > stem\LimCL.stm
porter-stemmer stop\LimSL.stp > stem\LimSL.stm
porter-stemmer stop\LimS.stp > stem\LimS.stm
porter-stemmer stop\LingLH.stp > stem\LingLH.stm
porter-stemmer stop\LoH.stp > stem\LoH.stm
porter-stemmer stop\LokCY.stp > stem\LokCY.stm
porter-stemmer stop\LoV.stp > stem\LoV.stm
porter-stemmer stop\McCardleR.stp > stem\McCardleR.stm
porter-stemmer stop\McKayM.stp > stem\McKayM.stm
porter-stemmer stop\MohdNasir.stp > stem\MohdNasir.stm
porter-stemmer stop\MohdSarit.stp > stem\MohdSarit.stm
porter-stemmer stop\MoN.stp > stem\MoN.stm
porter-stemmer stop\MorganC.stp > stem\MorganC.stm
porter-stemmer stop\MurrianR.stp > stem\MurrianR.stm
porter-stemmer stop\NelsonJ.stp > stem\NelsonJ.stm
porter-stemmer stop\NgTA.stp > stem\NgTA.stm
porter-stemmer stop\NgWC.stp > stem\NgWC.stm
porter-stemmer stop\NyagoA.stp > stem\NyagoA.stm
porter-stemmer stop\OkorieV.stp > stem\OkorieV.stm
porter-stemmer stop\OlomofeO.stp > stem\OlomofeO.stm
porter-stemmer stop\PalmerG.stp > stem\PalmerG.stm
porter-stemmer stop\PangCVA.stp > stem\PangCVA.stm
porter-stemmer stop\PangG.stp > stem\PangG.stm
porter-stemmer stop\PargeterA.stp > stem\PargeterA.stm
porter-stemmer stop\PonsamritN.stp > stem\PonsamritN.stm
porter-stemmer stop\PopadapoulosK.stp > stem\PopadapoulosK.stm
porter-stemmer stop\RajaI.stp > stem\RajaI.stm
porter-stemmer stop\RobertsonA.stp > stem\RobertsonA.stm
porter-stemmer stop\RobertsSM.stp > stem\RobertsSM.stm
porter-stemmer stop\RossiterJ.stp > stem\RossiterJ.stm
porter-stemmer stop\SamuelPNEW.stp > stem\SamuelPNEW.stm
porter-stemmer stop\SamuelP.stp > stem\SamuelP.stm
porter-stemmer stop\SchutzP.stp > stem\SchutzP.stm
porter-stemmer stop\ShahJ.stp > stem\ShahJ.stm
porter-stemmer stop\SodenJ.stp > stem\SodenJ.stm
porter-stemmer stop\SoonV.stp > stem\SoonV.stm
porter-stemmer stop\specification-Lam.stp > stem\specification-Lam.stm
porter-stemmer stop\SriskandarajahA.stp > stem\SriskandarajahA.stm
porter-stemmer stop\SwantstonD.stp > stem\SwantstonD.stm
porter-stemmer stop\TanPSN.stp > stem\TanPSN.stm
porter-stemmer stop\TanSMS.stp > stem\TanSMS.stm
porter-stemmer stop\TiongY.stp > stem\TiongY.stm
porter-stemmer stop\TngL.stp > stem\TngL.stm
porter-stemmer stop\TohTS.stp > stem\TohTS.stm
porter-stemmer stop\TomlinsonM.stp > stem\TomlinsonM.stm
porter-stemmer stop\TowersL.stp > stem\TowersL.stm
porter-stemmer stop\TsangB.stp > stem\TsangB.stm
porter-stemmer stop\WangMY.stp > stem\WangMY.stm
porter-stemmer stop\WangWS.stp > stem\WangWS.stm
porter-stemmer stop\WangW.stp > stem\WangW.stm
porter-stemmer stop\WilliamsJ.stp > stem\WilliamsJ.stm
porter-stemmer stop\WongCY.stp > stem\WongCY.stm
porter-stemmer stop\WongK.stp > stem\WongK.stm
porter-stemmer stop\WongWS.stp > stem\WongWS.stm
porter-stemmer stop\YaseenU.stp > stem\YaseenU.stm
porter-stemmer stop\YeapKS.stp > stem\YeapKS.stm
porter-stemmer stop\YiuMLM.stp > stem\YiuMLM.stm
porter-stemmer stop\ZhangJ.stp > stem\ZhangJ.stm
