stop stopList50 beng\AbassiM.txt > stop\AbassiM.stp
stop stopList50 beng\AgricoleW.txt > stop\AgricoleW.stp
stop stopList50 beng\AliR.txt > stop\AliR.stp
stop stopList50 beng\AngCX.txt > stop\AngCX.stp
stop stopList50 beng\AngeloZ.txt > stop\AngeloZ.stp
stop stopList50 beng\AppadooD.txt > stop\AppadooD.stp
stop stopList50 beng\BenHasineA.txt > stop\BenHasineA.stp
stop stopList50 beng\BenssiN.txt > stop\BenssiN.stp
stop stopList50 beng\BhagatR.txt > stop\BhagatR.stp
stop stopList50 beng\BradyE.txt > stop\BradyE.stp
stop stopList50 beng\BriarsC.txt > stop\BriarsC.stp
stop stopList50 beng\Broadhurst.txt > stop\Broadhurst.stp
stop stopList50 beng\BronksA.txt > stop\BronksA.stp
stop stopList50 beng\BrownL.txt > stop\BrownL.stp
stop stopList50 beng\ChanaG.txt > stop\ChanaG.stp
stop stopList50 beng\ChanCK.txt > stop\ChanCK.stp
stop stopList50 beng\ChanWK.txt > stop\ChanWK.stp
stop stopList50 beng\CheangF.txt > stop\CheangF.stp
stop stopList50 beng\ChengLC.txt > stop\ChengLC.stp
stop stopList50 beng\ChewCH.txt > stop\ChewCH.stp
stop stopList50 beng\ChongJYH.txt > stop\ChongJYH.stp
stop stopList50 beng\ChongKV.txt > stop\ChongKV.stp
stop stopList50 beng\ChongL.txt > stop\ChongL.stp
stop stopList50 beng\CollingsM.txt > stop\CollingsM.stp
stop stopList50 beng\CollisC.txt > stop\CollisC.stp
stop stopList50 beng\DiamantopoulosG.txt > stop\DiamantopoulosG.stp
stop stopList50 beng\DongP.txt > stop\DongP.stp
stop stopList50 beng\EdwinO.txt > stop\EdwinO.stp
stop stopList50 beng\EftekhariS.txt > stop\EftekhariS.stp
stop stopList50 beng\EvansA.txt > stop\EvansA.stp
stop stopList50 beng\fileList fileList
stop stopList50 beng\FooKSNEW.txt > stop\FooKSNEW.stp
stop stopList50 beng\Form.txt > stop\Form.stp
stop stopList50 beng\HaskellS.txt > stop\HaskellS.stp
stop stopList50 beng\HayatB.txt > stop\HayatB.stp
stop stopList50 beng\HengKK.txt > stop\HengKK.stp
stop stopList50 beng\HicksJ.txt > stop\HicksJ.stp
stop stopList50 beng\HoJW.txt > stop\HoJW.stp
stop stopList50 beng\HowlettA.txt > stop\HowlettA.stp
stop stopList50 beng\HughesP.txt > stop\HughesP.stp
stop stopList50 beng\JavaidMT.txt > stop\JavaidMT.stp
stop stopList50 beng\JiangS.txt > stop\JiangS.stp
stop stopList50 beng\JohalS.txt > stop\JohalS.stp
stop stopList50 beng\KallayT.txt > stop\KallayT.stp
stop stopList50 beng\KhanS.txt > stop\KhanS.stp
stop stopList50 beng\KhayumM.txt > stop\KhayumM.stp
stop stopList50 beng\KijakM.txt > stop\KijakM.stp
stop stopList50 beng\KoL.txt > stop\KoL.stp
stop stopList50 beng\KupusamyS.txt > stop\KupusamyS.stp
stop stopList50 beng\LaiYK.txt > stop\LaiYK.stp
stop stopList50 beng\LamC.txt > stop\LamC.stp
stop stopList50 beng\LamD.txt > stop\LamD.stp
stop stopList50 beng\LauEWF.txt > stop\LauEWF.stp
stop stopList50 beng\LeongJ.txt > stop\LeongJ.stp
stop stopList50 beng\LiC.txt > stop\LiC.stp
stop stopList50 beng\LimCL.txt > stop\LimCL.stp
stop stopList50 beng\LimSL.txt > stop\LimSL.stp
stop stopList50 beng\LimS.txt > stop\LimS.stp
stop stopList50 beng\LingLH.txt > stop\LingLH.stp
stop stopList50 beng\LoH.txt > stop\LoH.stp
stop stopList50 beng\LokCY.txt > stop\LokCY.stp
stop stopList50 beng\LoV.txt > stop\LoV.stp
stop stopList50 beng\McCardleR.txt > stop\McCardleR.stp
stop stopList50 beng\McKayM.txt > stop\McKayM.stp
stop stopList50 beng\MohdNasir.txt > stop\MohdNasir.stp
stop stopList50 beng\MohdSarit.txt > stop\MohdSarit.stp
stop stopList50 beng\MoN.txt > stop\MoN.stp
stop stopList50 beng\MorganC.txt > stop\MorganC.stp
stop stopList50 beng\MurrianR.txt > stop\MurrianR.stp
stop stopList50 beng\NelsonJ.txt > stop\NelsonJ.stp
stop stopList50 beng\NgTA.txt > stop\NgTA.stp
stop stopList50 beng\NgWC.txt > stop\NgWC.stp
stop stopList50 beng\NyagoA.txt > stop\NyagoA.stp
stop stopList50 beng\OkorieV.txt > stop\OkorieV.stp
stop stopList50 beng\OlomofeO.txt > stop\OlomofeO.stp
stop stopList50 beng\PalmerG.txt > stop\PalmerG.stp
stop stopList50 beng\PangCVA.txt > stop\PangCVA.stp
stop stopList50 beng\PangG.txt > stop\PangG.stp
stop stopList50 beng\PargeterA.txt > stop\PargeterA.stp
stop stopList50 beng\PonsamritN.txt > stop\PonsamritN.stp
stop stopList50 beng\PopadapoulosK.txt > stop\PopadapoulosK.stp
stop stopList50 beng\RajaI.txt > stop\RajaI.stp
stop stopList50 beng\RobertsonA.txt > stop\RobertsonA.stp
stop stopList50 beng\RobertsSM.txt > stop\RobertsSM.stp
stop stopList50 beng\RossiterJ.txt > stop\RossiterJ.stp
stop stopList50 beng\SamuelPNEW.txt > stop\SamuelPNEW.stp
stop stopList50 beng\SamuelP.txt > stop\SamuelP.stp
stop stopList50 beng\SchutzP.txt > stop\SchutzP.stp
stop stopList50 beng\ShahJ.txt > stop\ShahJ.stp
stop stopList50 beng\SodenJ.txt > stop\SodenJ.stp
stop stopList50 beng\SoonV.txt > stop\SoonV.stp
stop stopList50 beng\specification-Lam.txt > stop\specification-Lam.stp
stop stopList50 beng\SriskandarajahA.txt > stop\SriskandarajahA.stp
stop stopList50 beng\SwantstonD.txt > stop\SwantstonD.stp
stop stopList50 beng\TanPSN.txt > stop\TanPSN.stp
stop stopList50 beng\TanSMS.txt > stop\TanSMS.stp
stop stopList50 beng\TiongY.txt > stop\TiongY.stp
stop stopList50 beng\TngL.txt > stop\TngL.stp
stop stopList50 beng\TohTS.txt > stop\TohTS.stp
stop stopList50 beng\TomlinsonM.txt > stop\TomlinsonM.stp
stop stopList50 beng\TowersL.txt > stop\TowersL.stp
stop stopList50 beng\TsangB.txt > stop\TsangB.stp
stop stopList50 beng\WangMY.txt > stop\WangMY.stp
stop stopList50 beng\WangWS.txt > stop\WangWS.stp
stop stopList50 beng\WangW.txt > stop\WangW.stp
stop stopList50 beng\WilliamsJ.txt > stop\WilliamsJ.stp
stop stopList50 beng\WongCY.txt > stop\WongCY.stp
stop stopList50 beng\WongK.txt > stop\WongK.stp
stop stopList50 beng\WongWS.txt > stop\WongWS.stp
stop stopList50 beng\YaseenU.txt > stop\YaseenU.stp
stop stopList50 beng\YeapKS.txt > stop\YeapKS.stp
stop stopList50 beng\YiuMLM.txt > stop\YiuMLM.stp
stop stopList50 beng\ZhangJ.txt > stop\ZhangJ.stp
